---
i3wm:
    - alsa-utils
    - archlinux-wallpaper
    - arandr
    - dmenu
    - dunst
    - feh
    - flameshot
    - i3-wm
    - i3status
    - i3blocks
    - libinput
    - mate-backgrounds
    - maim
    - xclip
    - nitrogen
    - nm-connection-editor
    - lxappearance
    - nemo
    - picom
    - playerctl
    - polkit-gnome
    - ranger
    - rofi
    - ttf-font-awesome
    - ttf-droid
    - volumeicon
    - xterm
    - rxvt-unicode
    - xautolock
    - xfce4-power-manager
    - acpilight
 #   - xorg-xbacklight

i3wm_paru:
    - i3lock-color
    - i3-scrot
    - lightdm-settings
