---
- name: Clone yay repository
  git: repo=https://aur.archlinux.org/yay.git dest=/tmp/yay/ accept_hostkey=yes update=yes
  become_user: "{{ user.name }}"

- name: Create package
  shell: cd /tmp/yay && makepkg -si --noconfirm
  become_user: "{{ user.name }}"

- name: Install aur packages
  shell: yay --noconfirm -S {{ item }}
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - "{{ list_of_packages }}" 

