---
- name: Install packages
  pacman: name={{ item }} state=present
  with_items:
    - ['{{ grub }}']
    - ['{{ kernel }}']
    - ['{{ drivers }}']
    - ['{{ lib }}']
    - ['{{ Xorg }}']
    - ['{{ editor }}']
    - ['{{ file_system }}']
    - ['{{ bash }}']
    - ['{{ dev }}']
    - ['{{ sys }}']
