---
# tasks file for config
- name: Copy file for disabling beep in terminal
  copy:
     src: nobeep.conf
     dest: /etc/modprobe.d/nobeep.conf
     owner: root
     group: root
     mode: '0644'

- name: get value
  shell:
    cmd: lspci  | grep -ic RTL8723BE
  register: grep_output
  ignore_errors: yes
  changed_when: false

- name: Print
  debug:
    var="grep_output.stdout_lines"

- name: Copy config file for RTL8723BE Wifi adapter
  copy:
     src: rtl8723be.conf
     dest: /etc/modprobe.d/rtl8723be.conf
     owner: root
     group: root
     mode: '0644'
  when: grep_output.stdout == '1'

- name: Check ILoveCandy in pacman.conf
  shell:
    cmd: grep -ic ILoveCandy /etc/pacman.conf
  register: grep_candy
  ignore_errors: true
  changed_when: false
  failed_when: grep_candy.rc not in [ 0, 1 ]

- name: addline ILoveCandy
  lineinfile:
    dest: "/etc/pacman.conf"
    insertafter: '\[options\]'
    line: "ILoveCandy"
  when: grep_candy.stdout == '0'

- name: Check Color in pacman.conf
  shell:
    cmd: grep ^Color -c /etc/pacman.conf
  register: grep_color
  ignore_errors: true
  changed_when: false
  failed_when: grep_color.rc not in [ 0, 1 ]

- name: addline Color
  lineinfile:
    dest: "/etc/pacman.conf"
    insertafter: '\[options\]'
    line: "Color"
  when: grep_color.stdout == '0'

