---
- name: folders tasks
  tags: folders
  block:
  
  - name: Directory
    ansible.builtin.file:
      name: /home/{{ user.name }}/{{ item }}
      state: directory
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
    with_items:
      - Documents
      - Downloads
      - Pictures
      - Public
      - Templates
      - Videos
