---
- name: Install packages
  pacman: name={{ item }} state=present
  with_items:
    - ['{{ i3wm }}']

- name: Install aur packages
  shell: yay --noconfirm -S {{ item }}
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - "{{ i3wm-yay }}"

- name: Create xinitrc file
  copy:
    src: files/xinitrc
    dest: "{{ user.home }}/.xinitrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'

- name: Clone a github repository
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: "{{ user.home }}/.config/i3blocks-contrib"
    clone: yes
    update: yes
