---
- name: vbox tasks
  tags: vbox
  block:
  - name: Install packages
    ansible.builtin.pacman: name={{ item }} state=present
    with_items:
      - ['{{ vbox }}']
  
  - name: enable service vbox
    ansible.builtin.systemd:
      name: vboxservice
      state: started
      enabled: yes
  
  - name: enable modules
    ansible.builtin.shell:
      cmd: modprobe -a vboxguest vboxsf vboxvideo 
