---
- name: services tasks
  tags: services
  block:
  - name: NetworkManager service enable
    become: yes
    become_user: root
    become_method: sudo
  
    ansible.builtin.systemd:
      name: NetworkManager
      state: started
      enabled: yes
  
    #ansible.builtin.systemd:
    #  name: cups-browsed.service
    #  state: started
    #  enabled: yes
