---
- name: NetworkManager service enable
  become: yes
  become_user: root
  become_method: sudo

  systemd:
    name: NetworkManager
    state: started
    enabled: yes

  systemd:
    name: cups-browsed.service
    state: started
    enabled: yes

