---
grub:
    - grub
    - grub-customizer
    - os-prober
kernel:
    - linux
    - linux-firmware
#    - linux-lts
#    - linux-lts-headers
desktop:
    - archlinux-wallpaper
drivers:
    - hplip
    - xf86-video-nouveau
    - xf86-video-vesa
    - usb_modeswitch
    - mobile-broadband-provider-info
    - modemmanager
    - nm-connection-editor
lib:
    - libdvdread
    - libdvdcss
    - libdvdnav
    - python-configobj
Xorg:
    - xorg-server
    - xorg-xinit
    - xf86-input-synaptics
    - xf86-input-libinput
editor:
    - vim
file_system:
    - cifs-utils
    - libmtp
    - gvfs-smb
    - gvfs-mtp
    - mtpfs
    - nfs-utils
    - ntfs-3g
    - samba
bash:
    - bash-completion
    - neofetch
    - tree
dev:
    - code
sys:
    - bind-tools
    - curl
    - dialog
    - docker
    - fakeroot
    - geoip
    - git
    #- gnome-terminal
    - keychain
    - htop
    - inetutils 
    - lsof
    - man-db
    - mlocate
    - ncdu
    - net-tools
    - netctl
    - openssh
    - pacman-contrib
    - rsync
    - smbclient
    - smartmontools
    - sslscan
    - tcpdump
    - terminator
    - usbutils
    - whois
    - wget
